-- local cmp = require("cmp")
--
-- cmp.setup({
-- 	sources = cmp.config.sources({
-- 		{ name = "nvim_lsp" },
-- 		{ name = "path" },
-- 		{ name = "buffer" },
-- 	}),
-- 	mapping = cmp.mapping.preset.insert({
-- 		["<Tab>"] = { i = vim.NIL },
-- 		["<S-Tab>"] = vim.NIL,
-- 	}),
-- })
